controller_manager:
  ros__parameters:
    update_rate: 100
    diff_controller:
      type: diff_drive_controller/DiffDriveController

diff_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3
    wheel_radius: 0.05
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    publish_odom: true
    publish_cmd_vel: false